exec-once = /nix/store/lww2khz04qsc8prjp8l0haldwz15yivi-dbus-1.14.10/bin/dbus-update-activation-environment --systemd DISPLAY HYPRLAND_INSTANCE_SIGNATURE WAYLAND_DISPLAY XDG_CURRENT_DESKTOP && systemctl --user stop hyprland-session.target && systemctl --user start hyprland-session.target
#exec-once = bash ~/.config/hypr start.sh
exec-once = hyprpaper

source=~/.config/hypr/scripts/keybinds.conf
source=~/.config/hypr/scripts/displays.conf
source=~/.config/hypr/scripts/general.conf
